export const equipmentslists = [
    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Chave de fenda, se o veículo possuir calota',
        typeEsAr: 'Destornillador, si el vehículo tiene tapacubos',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/fenda.png"),
    },
    {
        typePtBr: 'Chave de roda',
        typeEsAr: 'Llave de ajuste / de rueda / de cruz / de cruceta',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/chave-de-roda.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo dispone de dispositivo de enganche de remolque ligero',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Macaco compatível',
        typeEsAr: 'Gato hidráulico compatible',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/macaco-hidraulico.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus (limites de carga, dimensões,velocidade, TWI, 1,6mm, recomendado fabricante)',
        typeEsAr: 'Neumáticos (límites de carga, dimensiones, velocidad, TWI, 1,6mm, recomendado por el fabricante)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Roda sobressalente',
        typeEsAr: 'Rueda de repuesto',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu (1).png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca), proibida instalação em reboque e semirreboque',
        typeEsAr: 'Faros (blancos), prohibida la instalación en remolques y semirremolques',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de advertência (na cor âmbar), facultado em reboque e semirreboque',
        typeEsAr: 'Luz de advertencia (ámbar), opcional en remolques y semirremolques',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/luz-advertencia.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/argentina.png"),
        country: "Argentina",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Chave de fenda, se o veículo possuir calota',
        typeEsAr: 'Destornillador, si el vehículo tiene tapacubos',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/fenda.png"),
    },
    {
        typePtBr: 'Chave de roda',
        typeEsAr: 'Llave de ajuste / de rueda / de cruz / de cruceta',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/chave-de-roda.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo dispone de dispositivo de enganche de remolque ligero',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Macaco compatível',
        typeEsAr: 'Gato hidráulico compatible',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/macaco-hidraulico.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus (limites de carga, dimensões,velocidade, TWI, 1,6mm, recomendado fabricante)',
        typeEsAr: 'Neumáticos (límites de carga, dimensiones, velocidad, TWI, 1,6mm, recomendado por el fabricante)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Roda sobressalente',
        typeEsAr: 'Rueda de repuesto',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu (1).png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca), proibida instalação em reboque e semirreboque',
        typeEsAr: 'Faros (blancos), prohibida la instalación en remolques y semirremolques',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de advertência (na cor âmbar), facultado em reboque e semirreboque',
        typeEsAr: 'Luz de advertencia (ámbar), opcional en remolques y semirremolques',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/luz-advertencia.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/paraguai.png"),
        country: "Paraguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Chave de fenda, se o veículo possuir calota',
        typeEsAr: 'Destornillador, si el vehículo tiene tapacubos',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/fenda.png"),
    },
    {
        typePtBr: 'Chave de roda',
        typeEsAr: 'Llave de ajuste / de rueda / de cruz / de cruceta',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/chave-de-roda.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo dispone de dispositivo de enganche de remolque ligero',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Macaco compatível',
        typeEsAr: 'Gato hidráulico compatible',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/macaco-hidraulico.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus (limites de carga, dimensões, velocidade, TWI, 1,6mm, recomendado fabricante)',
        typeEsAr: 'Neumáticos (límites de carga, dimensiones, velocidad, TWI, 1,6mm, recomendado por el fabricante)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Roda sobressalente',
        typeEsAr: 'Rueda de repuesto',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu (1).png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca), proibida instalação em reboque e semirreboque',
        typeEsAr: 'Faros (blancos), prohibida la instalación en remolques y semirremolques',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de advertência (na cor âmbar), facultado em reboque e semirreboque',
        typeEsAr: 'Luz de advertencia (ámbar), opcional en remolques y semirremolques',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/luz-advertencia.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/uruguai.png"),
        country: "Uruguai",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Chave de fenda, se o veículo possuir calota',
        typeEsAr: 'Destornillador, si el vehículo tiene tapacubos',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/fenda.png"),
    },
    {
        typePtBr: 'Chave de roda',
        typeEsAr: 'Llave de ajuste / de rueda / de cruz / de cruceta',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/chave-de-roda.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo dispone de dispositivo de enganche de remolque ligero',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Macaco compatível',
        typeEsAr: 'Gato hidráulico compatible',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/macaco-hidraulico.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus (limites de carga, dimensões,velocidade, TWI, 1,6mm, recomendado fabricante)',
        typeEsAr: 'Neumáticos (límites de carga, dimensiones, velocidad, TWI, 1,6mm, recomendado por el fabricante)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Roda sobressalente',
        typeEsAr: 'Rueda de repuesto',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/pneu (1).png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca), proibida instalação em reboque e semirreboque',
        typeEsAr: 'Faros (blancos), prohibida la instalación en remolques y semirremolques',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de advertência (na cor âmbar), facultado em reboque e semirreboque',
        typeEsAr: 'Luz de advertencia (ámbar), opcional en remolques y semirremolques',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/luz-advertencia.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/venezuela.png"),
        country: "Venezuela",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo dispone de dispositivo de enganche de remolque ligero',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/bolivia.png"),
        country: "Bolívia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo tiene dispositivo de enganche para remolque ligero',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/chile.png"),
        country: "Chile",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo tiene dispositivo de enganche para remolque liviano',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de mano',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/colombia.png"),
        country: "Colômbia",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo tiene dispositivo de acople para remolque ligero',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de mano',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/equador.png"),
        country: "Equador",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo tiene dispositivo de enganche para remolque ligero',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/peru.png"),
        country: "Peru",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo tiene dispositivo de enganche para remolque liviano',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/close.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/close.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/guiana.png"),
        country: "Guiana",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },

    {
        typePtBr: 'Buzina',
        typeEsAr: 'Bocina / claxon / pito',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/volume.png"),
    },
    {
        typePtBr: 'Cinto de Segurança',
        typeEsAr: 'Cinturón de seguridad',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/safety-belt.png"),
    },
    {
        typePtBr: 'Corrente ou cabo, caso o veículo esteja com dispositivo de engate de reboque ligeiro',
        typeEsAr: 'Cadena o cable, si el vehículo tiene dispositivo de acople para remolque ligero',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/ligacao.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (apenas um)',
        typeEsAr: 'Espejo retrovisor (solo uno)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/espelho-retrovisor.png"),
    },
    {
        typePtBr: 'Espelho retrovisor (dois)',
        typeEsAr: 'Espejos retrovisores (dos)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/espelho-retrovisores.png"),
    },
    {
        typePtBr: 'Extintor de incêndio',
        typeEsAr: 'Extintor de incendios / matafuegos',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/extintor.png"),
    },
    {
        typePtBr: 'Freio de estacionamento',
        typeEsAr: 'Freno de estacionamiento',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/freio-de-mao.png"),
    },
    {
        typePtBr: 'Freio de serviço',
        typeEsAr: 'Freno de servicio',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/freio.png"),
    },
    {
        typePtBr: 'Lavador de para-brisa',
        typeEsAr: 'Lavador de parabrisas',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa.png"),
    },
    {
        typePtBr: 'Limpador de para-brisa (pelo menos um)',
        typeEsAr: 'Limpiaparabrisas (al menos uno)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/parabrisa-limpador.png"),
    },
    {
        typePtBr: 'Para-brisa',
        typeEsAr: 'Parabrisas',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/para-brisas.png"),
    },
    {
        typePtBr: 'Para-choques (dianteiro e traseiro)',
        typeEsAr: 'Parachoques (delantero y trasero)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/para-choque-traseiro.png"),
    },
    {
        typePtBr: 'Pneus',
        typeEsAr: 'Neumáticos',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/pneu.png"),
    },
    {
        typePtBr: 'Silenciador de explosão',
        typeEsAr: 'Silenciador de explosiones',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/escape.png"),
    },
    {
        typePtBr: 'Triângulo',
        typeEsAr: 'Triángulo de advertencia',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/triangulo.png"),
    },
    {
        typePtBr: 'Velocímetro',
        typeEsAr: 'Velocímetro',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/radar-de-velocidade.png"),
    },
    {
        typePtBr: 'Faróis (na cor branca ou amarela)',
        typeEsAr: 'Faros (blancos o amarillos)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz indicadora de direção dianteira e traseira (na cor âmbar)',
        typeEsAr: 'Luz intermitente delantera y trasera (color ámbar)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-lateral.png"),
    },
    {
        typePtBr: 'Lanterna de luz de freio (na cor vermelha)',
        typeEsAr: 'Luz de freno (color rojo)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-forte.png"),
    },
    {
        typePtBr: 'Lanterna de luz de marcha-a-ré (na cor branca), opcional em reboque e semirreboque',
        typeEsAr: 'Luz de marcha atrás (blanca), opcional en remolques y semirremolques',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/close.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de placa (na cor branca)',
        typeEsAr: 'Luz de matrícula (blanca)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás-ré.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor branca à frente)',
        typeEsAr: 'Luz de posición (blanca al frente)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-sedan-na-frente.png"),
    },
    {
        typePtBr: 'Lanterna de luz de posição (na cor vermelha na traseira)',
        typeEsAr: 'Luz de posición (roja en la parte trasera)',
        uri: require("../icons/suriname.png"),
        country: "Suriname",
        check: require("../icons/check.png"),
        icon: require("../icons/carro-atrás.png"),
    },
]
